// ─────────────────────────────────────────────────────────
// GEMSTONE KNOWLEDGE BASE
// Used by the recommendation engine to score and rank gems
// ─────────────────────────────────────────────────────────

export const GEMSTONES = [
  {
    id: 'ruby',
    name: 'Ruby',
    color: 'Deep Red',
    planet: 'Sun',
    chakra: 'Root',
    zodiacSigns: ['Leo', 'Aries', 'Scorpio'],
    needs: ['confidence', 'leadership', 'energy', 'passion', 'vitality'],
    minBudget: 1500,
    description:
      'Ruby is the stone of passion and vitality. Associated with the Sun, it boosts confidence, leadership, and life force energy. Ideal for those seeking courage and clarity of purpose.',
    benefits: ['Boosts self-confidence', 'Enhances leadership qualities', 'Promotes vitality and energy', 'Attracts prosperity'],
    careInstructions: 'Clean with warm soapy water. Avoid harsh chemicals. Recharge under sunlight.',
    origin: ['Myanmar', 'Thailand', 'Sri Lanka'],
    hardness: '9 (Mohs)',
    priceRange: { min: 1500, max: 50000 },
    imageEmoji: '🔴',
  },
  {
    id: 'emerald',
    name: 'Emerald',
    color: 'Rich Green',
    planet: 'Mercury',
    chakra: 'Heart',
    zodiacSigns: ['Taurus', 'Gemini', 'Virgo', 'Cancer'],
    needs: ['love', 'healing', 'growth', 'communication', 'clarity', 'wisdom'],
    minBudget: 2000,
    description:
      'Emerald is the stone of successful love and wisdom. It opens the heart chakra, enhances communication, and promotes emotional healing and intellectual growth.',
    benefits: ['Enhances communication', 'Promotes emotional healing', 'Attracts love and harmony', 'Sharpens intellect'],
    careInstructions: 'Clean gently with mild soap. Avoid ultrasonic cleaners. Store separately to prevent scratches.',
    origin: ['Colombia', 'Zambia', 'Brazil'],
    hardness: '7.5–8 (Mohs)',
    priceRange: { min: 2000, max: 80000 },
    imageEmoji: '💚',
  },
  {
    id: 'sapphire',
    name: 'Blue Sapphire',
    color: 'Royal Blue',
    planet: 'Saturn',
    chakra: 'Third Eye',
    zodiacSigns: ['Capricorn', 'Aquarius', 'Virgo', 'Libra'],
    needs: ['focus', 'discipline', 'career', 'protection', 'wisdom', 'clarity'],
    minBudget: 3000,
    description:
      'Blue Sapphire is one of the most powerful gemstones, associated with Saturn. It brings focus, discipline, career success, and protection from negative energies.',
    benefits: ['Improves focus and concentration', 'Boosts career and ambitions', 'Provides protection', 'Enhances intuition'],
    careInstructions: 'Clean with warm soapy water. Safe for ultrasonic cleaners. Recharge under moonlight.',
    origin: ['Kashmir', 'Sri Lanka', 'Myanmar'],
    hardness: '9 (Mohs)',
    priceRange: { min: 3000, max: 100000 },
    imageEmoji: '💙',
  },
  {
    id: 'amethyst',
    name: 'Amethyst',
    color: 'Purple',
    planet: 'Jupiter',
    chakra: 'Crown',
    zodiacSigns: ['Pisces', 'Aquarius', 'Sagittarius', 'Capricorn'],
    needs: ['calm', 'peace', 'stress', 'spiritual', 'sleep', 'meditation', 'anxiety'],
    minBudget: 200,
    description:
      'Amethyst is a powerful protective and calming stone. It promotes tranquility, relieves stress, aids sleep, and enhances spiritual awareness and meditation.',
    benefits: ['Reduces stress and anxiety', 'Improves sleep quality', 'Enhances spiritual connection', 'Promotes emotional balance'],
    careInstructions: 'Clean with mild soap and water. Avoid prolonged sunlight as it may fade the color.',
    origin: ['Brazil', 'Uruguay', 'Zambia'],
    hardness: '7 (Mohs)',
    priceRange: { min: 200, max: 5000 },
    imageEmoji: '💜',
  },
  {
    id: 'rose_quartz',
    name: 'Rose Quartz',
    color: 'Soft Pink',
    planet: 'Venus',
    chakra: 'Heart',
    zodiacSigns: ['Taurus', 'Libra', 'Cancer', 'Pisces'],
    needs: ['love', 'self-love', 'relationships', 'healing', 'compassion', 'peace'],
    minBudget: 100,
    description:
      'Rose Quartz is the ultimate stone of unconditional love. It opens the heart chakra, encourages self-love, heals emotional wounds, and attracts romantic and platonic love.',
    benefits: ['Attracts love and romance', 'Promotes self-love and acceptance', 'Heals emotional trauma', 'Encourages compassion'],
    careInstructions: 'Clean with mild soap and water. Charge under moonlight. Handle gently to avoid scratches.',
    origin: ['Brazil', 'Madagascar', 'South Africa'],
    hardness: '7 (Mohs)',
    priceRange: { min: 100, max: 3000 },
    imageEmoji: '🌸',
  },
  {
    id: 'citrine',
    name: 'Citrine',
    color: 'Golden Yellow',
    planet: 'Sun',
    chakra: 'Solar Plexus',
    zodiacSigns: ['Gemini', 'Leo', 'Aries', 'Libra'],
    needs: ['abundance', 'prosperity', 'confidence', 'motivation', 'creativity', 'positivity'],
    minBudget: 300,
    description:
      'Citrine is known as the "Merchant\'s Stone" and attracts wealth, abundance, and success. It energises the solar plexus chakra, boosting motivation and creativity.',
    benefits: ['Attracts wealth and abundance', 'Boosts motivation and energy', 'Enhances creativity', 'Promotes positive thinking'],
    careInstructions: 'Clean with mild soap and water. Avoid prolonged heat exposure. Recharge in sunlight briefly.',
    origin: ['Brazil', 'Spain', 'Russia'],
    hardness: '7 (Mohs)',
    priceRange: { min: 300, max: 8000 },
    imageEmoji: '💛',
  },
  {
    id: 'pearl',
    name: 'Pearl',
    color: 'Lustrous White',
    planet: 'Moon',
    chakra: 'Crown',
    zodiacSigns: ['Cancer', 'Pisces', 'Scorpio'],
    needs: ['calm', 'emotional balance', 'intuition', 'purity', 'peace', 'sleep'],
    minBudget: 500,
    description:
      'Pearl is associated with the Moon and represents purity, emotional balance, and wisdom. It calms the mind, enhances intuition, and promotes inner peace.',
    benefits: ['Calms emotions and mind', 'Enhances intuition', 'Promotes purity and integrity', 'Improves emotional balance'],
    careInstructions: 'Wipe gently with soft cloth. Avoid chemicals, perfume, and prolonged water exposure. Store in soft pouch.',
    origin: ['Japan', 'China', 'Australia'],
    hardness: '2.5–3 (Mohs)',
    priceRange: { min: 500, max: 20000 },
    imageEmoji: '🤍',
  },
  {
    id: 'turquoise',
    name: 'Turquoise',
    color: 'Sky Blue-Green',
    planet: 'Venus & Neptune',
    chakra: 'Throat',
    zodiacSigns: ['Sagittarius', 'Pisces', 'Scorpio', 'Aquarius'],
    needs: ['communication', 'travel', 'protection', 'creativity', 'expression', 'luck'],
    minBudget: 400,
    description:
      'Turquoise is one of the oldest protection stones, used for centuries as a talisman. It enhances communication, expression, creativity, and provides strong protective energy.',
    benefits: ['Enhances communication', 'Provides protection during travel', 'Boosts creativity', 'Promotes honesty and clarity'],
    careInstructions: 'Avoid water and chemicals. Clean with dry soft cloth. Store away from other gemstones.',
    origin: ['Iran', 'USA', 'China', 'Tibet'],
    hardness: '5–6 (Mohs)',
    priceRange: { min: 400, max: 10000 },
    imageEmoji: '🩵',
  },
  {
    id: 'garnet',
    name: 'Garnet',
    color: 'Deep Crimson',
    planet: 'Mars',
    chakra: 'Root & Heart',
    zodiacSigns: ['Capricorn', 'Aries', 'Scorpio', 'Leo'],
    needs: ['energy', 'passion', 'grounding', 'strength', 'courage', 'vitality'],
    minBudget: 500,
    description:
      'Garnet is a stone of commitment, passion, and revitalising energy. It grounds the root chakra, provides strength, and ignites the fire of passion and purpose.',
    benefits: ['Revitalises energy and drive', 'Promotes courage and strength', 'Grounds and stabilises emotions', 'Ignites passion'],
    careInstructions: 'Clean with warm soapy water. Avoid steam cleaning. Recharge on earth or near plants.',
    origin: ['India', 'Russia', 'South Africa'],
    hardness: '6.5–7.5 (Mohs)',
    priceRange: { min: 500, max: 15000 },
    imageEmoji: '🍷',
  },
  {
    id: 'moonstone',
    name: 'Moonstone',
    color: 'Milky White / Blue Sheen',
    planet: 'Moon',
    chakra: 'Third Eye & Crown',
    zodiacSigns: ['Cancer', 'Libra', 'Scorpio', 'Pisces'],
    needs: ['intuition', 'feminine energy', 'new beginnings', 'emotional balance', 'sleep', 'spiritual'],
    minBudget: 600,
    description:
      'Moonstone is a stone of new beginnings, deeply connected to the moon and feminine energy. It enhances intuition, emotional balance, and is a powerful stone for new cycles in life.',
    benefits: ['Enhances intuition and psychic ability', 'Balances emotions', 'Supports new beginnings', 'Connects to feminine energy'],
    careInstructions: 'Clean with mild soap. Avoid ultrasonic cleaners. Recharge under moonlight for best effect.',
    origin: ['Sri Lanka', 'India', 'Madagascar'],
    hardness: '6–6.5 (Mohs)',
    priceRange: { min: 600, max: 12000 },
    imageEmoji: '🌙',
  },
  {
    id: 'lapis_lazuli',
    name: 'Lapis Lazuli',
    color: 'Deep Blue with Gold',
    planet: 'Jupiter',
    chakra: 'Third Eye & Throat',
    zodiacSigns: ['Sagittarius', 'Aquarius', 'Pisces'],
    needs: ['wisdom', 'truth', 'communication', 'intellectual', 'spiritual', 'clarity'],
    minBudget: 700,
    description:
      'Lapis Lazuli is the stone of truth, wisdom, and enlightenment. Used by ancient royals, it activates the intellectual mind and enhances the ability to express deep truths.',
    benefits: ['Enhances wisdom and intellect', 'Promotes truthful communication', 'Stimulates spiritual insight', 'Boosts memory'],
    careInstructions: 'Clean with dry or slightly damp cloth only. Avoid water and chemicals as they can damage the stone.',
    origin: ['Afghanistan', 'Chile', 'Russia'],
    hardness: '5–6 (Mohs)',
    priceRange: { min: 700, max: 18000 },
    imageEmoji: '🌌',
  },
  {
    id: 'tigers_eye',
    name: "Tiger's Eye",
    color: 'Golden Brown',
    planet: 'Sun & Mars',
    chakra: 'Solar Plexus & Root',
    zodiacSigns: ['Leo', 'Capricorn', 'Aries'],
    needs: ['confidence', 'focus', 'grounding', 'willpower', 'career', 'protection'],
    minBudget: 300,
    description:
      "Tiger's Eye combines earth and sun energies to create a high-vibrational stone that grounds while it motivates. It sharpens focus, boosts willpower, and provides clarity in decision-making.",
    benefits: ['Boosts confidence and willpower', 'Sharpens focus and clarity', 'Provides grounding energy', 'Protects against negativity'],
    careInstructions: 'Clean with mild soap and water. Recharge in sunlight. Handle carefully to avoid scratches.',
    origin: ['South Africa', 'Australia', 'India'],
    hardness: '7 (Mohs)',
    priceRange: { min: 300, max: 6000 },
    imageEmoji: '🐯',
  },
];

export const ZODIAC_SIGNS = [
  'Aries', 'Taurus', 'Gemini', 'Cancer',
  'Leo', 'Virgo', 'Libra', 'Scorpio',
  'Sagittarius', 'Capricorn', 'Aquarius', 'Pisces',
];

export const NEEDS_OPTIONS = [
  { value: 'love', label: 'Love & Relationships' },
  { value: 'confidence', label: 'Confidence & Self-esteem' },
  { value: 'career', label: 'Career & Ambition' },
  { value: 'calm', label: 'Calm & Stress Relief' },
  { value: 'spiritual', label: 'Spiritual Growth' },
  { value: 'healing', label: 'Healing & Wellness' },
  { value: 'prosperity', label: 'Wealth & Prosperity' },
  { value: 'protection', label: 'Protection & Safety' },
  { value: 'clarity', label: 'Mental Clarity & Focus' },
  { value: 'creativity', label: 'Creativity & Expression' },
  { value: 'communication', label: 'Communication' },
  { value: 'wisdom', label: 'Wisdom & Intuition' },
  { value: 'energy', label: 'Energy & Vitality' },
  { value: 'sleep', label: 'Sleep & Rest' },
  { value: 'new beginnings', label: 'New Beginnings' },
];
